# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalleespecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificaciontaxonomica', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcionlarga', models.CharField(blank=True, max_length=255, null=True)),
                ('nombrecientifico', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleespecieCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Categoria')),
                ('detalleespecie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Detalleespecie')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecieComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Comentario')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Especie')),
            ],
        ),
        migrations.AddField(
            model_name='detalleespecie',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Especie'),
        ),
    ]
