# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_especie_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleespecie',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='detalleespeciecategoria',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='detalleespeciecategoria',
            name='detalleespecie',
        ),
        migrations.RemoveField(
            model_name='especiecomentario',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='especiecomentario',
            name='especie',
        ),
        migrations.AddField(
            model_name='comentario',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Especie'),
        ),
        migrations.AddField(
            model_name='especie',
            name='clasificaciontaxonomica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='descripcionlarga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='nombrecientifico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='especie',
            name='foto',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Detalleespecie',
        ),
        migrations.DeleteModel(
            name='DetalleespecieCategoria',
        ),
        migrations.DeleteModel(
            name='EspecieComentario',
        ),
    ]
