# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170210_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='foto',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
