# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170211_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='foto',
            field=models.ImageField(null=True, upload_to='/static/media/images/'),
        ),
    ]
