# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='foto',
            field=models.ImageField(null=True, upload_to='reservanatural/static/media/images'),
        ),
    ]
