# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='static/media/images/no_foto.jpg', upload_to='static/media/images'),
        ),
    ]
