# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_userprofile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='images/no_foto.jpg', upload_to='images'),
        ),
    ]
